// apps/demo-angular/src/plugin-demos/firebase-app-check.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedFirebaseAppCheck } from '@demo/shared';
import {} from '@nativescript-asharghi/firebase-app-check';

@Component({
	selector: 'demo-firebase-app-check',
	templateUrl: 'firebase-app-check.component.html',
})
export class FirebaseAppCheckComponent {
	demoShared: DemoSharedFirebaseAppCheck;

	constructor(private _ngZone: NgZone) {}

	ngOnInit() {
		this.demoShared = new DemoSharedFirebaseAppCheck();
	}
}

<ActionBar title="firebase-app-check" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test firebase-app-check" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>

// apps/demo-vue/app/plugin-demos/firebase-app-check.vue
<template>
	<Page>
		<ActionBar>
			<Label text="firebase-app-check" />
		</ActionBar>

		<GridLayout>
			<Button class="info" :text="message" />
		</GridLayout>
	</Page>
</template>

<script lang="ts">
import Vue from 'nativescript-vue';
import { DemoSharedFirebaseAppCheck } from '@demo/shared';
import {} from '@nativescript-asharghi/firebase-app-check';

export default Vue.extend({
	computed: {
		message() {
			return 'Test firebase-app-check';
		},
	},
});
</script>

<style scoped lang="scss">
.info {
	font-size: 20;
	horizontal-align: center;
	vertical-align: center;
}
</style>
