// apps/demo-vue/app/plugin-demos/firebase-messaging-core.vue
<template>
	<Page>
		<ActionBar>
			<Label text="firebase-messaging-core" />
		</ActionBar>

		<GridLayout>
			<Button class="info" :text="message" />
		</GridLayout>
	</Page>
</template>

<script lang="ts">
import Vue from 'nativescript-vue';
import { DemoSharedFirebaseMessagingCore } from '@demo/shared';
import {} from '@nativescript-asharghi/firebase-messaging-core';

export default Vue.extend({
	computed: {
		message() {
			return 'Test firebase-messaging-core';
		},
	},
});
</script>

<style scoped lang="scss">
.info {
	font-size: 20;
	horizontal-align: center;
	vertical-align: center;
}
</style>

// apps/demo-angular/src/plugin-demos/firebase-messaging-core.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedFirebaseMessagingCore } from '@demo/shared';
import {} from '@nativescript-asharghi/firebase-messaging-core';

@Component({
	selector: 'demo-firebase-messaging-core',
	templateUrl: 'firebase-messaging-core.component.html',
})
export class FirebaseMessagingCoreComponent {
	demoShared: DemoSharedFirebaseMessagingCore;

	constructor(private _ngZone: NgZone) {}

	ngOnInit() {
		this.demoShared = new DemoSharedFirebaseMessagingCore();
	}
}

<ActionBar title="firebase-messaging-core" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test firebase-messaging-core" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>
